### PR TITLE
add Swoole async task

### PR DESCRIPTION
**Pull request by damonto**
[Issues#73](https://github.com/swooletw/laravel-swoole/issues/73)

You can use 

```
SwooleTask::async(function () {
     // async task
}); 

// or

swoole_async_task(function () {
    // async
});
```

to run an async task. For example you can send an E-Mail in an async task.

### CODE REVIEW

**Comment by albertcht** [comment]
Hi @damonto ,

Thanks a lot for your PR, what do you think if wrap swoole's async task functino as Laravel's queue driver? That would be more Laravel style. Like this: https://github.com/barryvdh/laravel-async-queue

**Comment by damonto** [comment]
@albertcht I think swoole's async task  is more like swoole's coroutine. If you invoke it. It will be executed immediately. But swoole's async task is running in the background not frontend.

**Comment by albertcht** [comment]
I understand that a dispatched async task will be processed by swoole's task worker right away. That doesn't matter. In this way Laravel developers can turn their existed queue jobs to swoole's async jobs by only configuring the driver.

**Comment by damonto** [comment]
It's possible. I'll be add it in the next few days. Thanks for you advice.

**Comment by albertcht** [comment]
Using swoole's async task as coroutine is difficult to achieve because this package will return Laravel's response to clients before async tasks complete. So I think it's more like Laravel's queue.

**Comment by albertcht** [comment]
No problem, and currently I'm refactoring this package in `coroutine_feature` branch. It will be great if you can add tests for this feature and merge to this branch. Thanks for your PR again. :)

**Comment by damonto** [comment]
I understand swoole's async task it's more like Laravel's Queue. `lt's more like coroutine` may be some ambiguous. In my view it's more like a function?  I wanted to add a test, but it seems impossible due to the async task will be processed by swoole's task right away. Do you have any idea?

**Comment by albertcht** [comment]
Unit tests are just fine.

**Comment by damonto** [comment]
```php
public function testAsyncTask() 
{
    $file = __DIR__ . '/tests.log';
    $sleepSeconds = 1;
    $beforeRunningTaskTime = time();

    app('swoole.task')->async(function () use ($file, $sleepSeconds) {
        sleep($sleepSeconds);
        file_put_contents($file, time());
    });

    $this->assertSame($beforeRunningTaskTime, file_get_contents($file) - $sleepSeconds);

    unlink($file);
}
```

What do you think of this?

**Comment by damonto** [comment]
I think so. let me think about how to test it

**Comment by albertcht** [comment]
Welcome comment below if you have any other questions or ideas. :)

**Comment by damonto** [comment]
@albertcht I'll be close this PR And I'll PR again because of the branch name.

**Pull request closed without merging**
