### PR TITLE
fix(request): static file MIME type

### PR DESCRIPTION
**Pull request by killtw**
Due to `mime_content_type` could not detect CSS file, it would return `text/plain`.
The browser could not parse it correctly. 

`Illuminate\Http\Testing` provide a class named `MimeType`, it includes common file mime type

### CODE REVIEW

**Comment by pehbehbeh** [comment]
We are also experiencing this issue with Laravel 5.7 and PHP 7.2 - would really appreciate this fix.

@killtw Did you notice the failing tests?

**FYI:** This workaround works for us:

```diff
    public static function handleStatic($swooleRequest, $swooleResponse, string $publicPath)
    {
        $uri = $swooleRequest->server['request_uri'] ?? '';
        $extension = pathinfo($uri, PATHINFO_EXTENSION);
        $fileName = $publicPath . $uri;
        if ($extension && in_array($extension, static::EXTENSION_BLACKLIST)) {
            return false;
        }
        if (! is_file($fileName) || ! filesize($fileName)) {
            return false;
        }
        $contentType = mime_content_type($fileName);
        $swooleResponse->status(IlluminateResponse::HTTP_OK);
-       $swooleResponse->header('Content-Type', static::EXTENSION_MIMES[$contentType] ?? $contentType);
+       $swooleResponse->header('Content-Type', static::EXTENSION_MIMES[$extension] ?? $contentType);
        $swooleResponse->sendfile($fileName);
        return true;
    }
```

**Comment by killtw** [comment]
@pehbehbeh I am figuring out how to cover all version of Laravel

**Comment by killtw** [comment]
@albertcht it should have finished, would you review it?

**Comment by albertcht** [comment]
Hi @killtw ,

Thanks for your pull request, I'll review it by this weekend :)

**Comment by albertcht** [comment]
Hi @killtw ,

Because `Illuminate\Http\Testing\MimeType` class only exists after Laravel 5.4, I'm thinking if copying the entire class to `SwooleTW\Http\Helpers` to support all the versions.

That can also avoid potential changes of `Illuminate\Http\Testing\MimeType` in the future versions.

**Pull request merged**
