### PR TITLE
Support Laravel v9 + Github Actions

### PR DESCRIPTION
**Pull request by alecpl**
I see that Travis tests aren't working. So, I configured Github Actions. Some tests are failing, but I hope this will help you to add Laravel v9 support. It looks that only one more test is failing with v9.

I'm unfortunately not familiar with this codebase so can't really fix these issues.

### CODE REVIEW

**Review by Cryental — APPROVED** [review]

**Comment by alecpl** [comment]
Thanks for looking into this. I'm not sure why the tests didn't run for this PR, maybe you have to enable something. You can find the tests results at https://github.com/alecpl/laravel-swoole/actions/runs/1860568484.

**Comment by romarioliveira25** [comment]
any news about merge it?

**Comment by Cryental** [comment]
Please merge this if possible. We are getting problems now because no lumen 9.x support :(

**Comment by onursahindur** [comment]
Need merge 😢

**Comment by Arkanius** [comment]
@alecpl That's really cool bro! Really thank you for doing that.

Sorry for my late reply here for all of you, I'm not in the best times...

Anyway, I'll merge it, tks!

**Pull request merged**
