### PR TITLE
Add Gzip support on response chunk mode

### PR DESCRIPTION
**Pull request by hezachary**
Swoole does not support compress on chunk mode, related document: https://wiki.swoole.com/#/http_server?id=http_compression

The patch provide gzip for such needs.

A example is AWS load balance in many cases can replace server like apache or nginx. However, ALB does not provide compression. Once swoole in chunk mode, there almost no other choice but to add a web server in between.

1. The patch checks Laravel/Lumen response header to avoid double compression
2. Only gzip when client side provide "accept-encoding" header with `gzip` option
3. Only gzip when Swoole config shows `http_compression = true`
4. Also, it checks zlib `gzencode` is installed

### CODE REVIEW

**Comment by RodrigoGalter** [comment]
Any idea when this will be approved?

**Comment by Arkanius** [comment]
I'm still reviewing it

**Comment by hezachary** [comment]
I will add more test case to increase coverage today, at least for my code.

**Comment by hezachary** [comment]
With the new test case, coverage for `SwooleTW\Http\Transformers/\Response`
[https://ibb.co/wBJ8488](url)

**Comment by hezachary** [comment]
Is there anything I can do to improve the PR to help you @Arkanius  approve it?

**Comment by Arkanius** [comment]
Thank you @hezachary ! I think that is ok! I'm planning to release it at this week

**Comment by Arkanius** [comment]
@hezachary it's now release as v2.7.0

Thanks for your support!

**Pull request merged**
