### PR TITLE
Support for Laravel 7

### PR DESCRIPTION
**Pull request by codercms**

### CODE REVIEW

**Comment by MostafaRabia** [comment]
Is it to install this package with laravel 7?

**Comment by codercms** [comment]
@MostafaRabia yes

**Comment by MostafaRabia** [comment]
@codercms 
Excuse me, how to use it?
I put the changes in composer.json at file vendor, and nothing with composer update...
How can i use it?

**Comment by codercms** [comment]
@MostafaRabia if you don't want to wait for a new release of this package, you can create a fork of this package with those changes. After that you can publish your fork on https://packagist.org/ and require it from composer.
Also you can do this without publishing your fork on packagist:
1. Add these lines to your composer.json
```
"repositories": [
    {
        "type": "vcs",
        "url": "your repo url, for example - https://github.com/codercms/laravel-swoole.git"
    }
],
```
2. Add to the "require" section: `"swooletw/laravel-swoole": "dev-master"` or choose another name of your package in the `composer.json` of your fork.

**Comment by MostafaRabia** [comment]
Very thanks!

**Comment by albertcht** [comment]
Sorry for late response, I've merged this pull request.
However, I'm not sure if it's 100% compatible with Laravel 7.
Welcome for any issues report if you find any on Laravel 7.

**Comment by nifengfanpan** [comment]
> 对不起，我的回复很晚，我已经合并了这个请求。
> 但是，我不确定它是否与Laravel 7 100％兼容。
> 如果在Laravel 7上发现任何问题，欢迎报告。
please for help
laravel7 ：Target class [swoole.websocket] does not exist.

**Comment by nifengfanpan** [comment]
> Sorry for late response, I've merged this pull request.
> However, I'm not sure if it's 100% compatible with Laravel 7.
> Welcome for any issues report if you find any on Laravel 7.

Excuse me
laravel7 ：Target class [swoole.websocket] does not exist.
please for help @albertcht @codercms @pedro-santiago

**Pull request merged**
