### PR TITLE
Update message attribute datatype in Pusher.php

### PR DESCRIPTION
**Pull request by mabdulazim**
update message attribute datatype to mixed rather than string to send json object as the data

### CODE REVIEW

**Comment by albertcht** [comment]
Hi @mabdulazim ,

A json encoded data should be string type as well. Can you show me more explicit example?

**Comment by mabdulazim** [comment]
@albertcht the default parser receives the second parameter as a string or array or object.
if i send a json encoded, the parser considers it a normal text and the broadcast doesn’t fire

**Comment by mabdulazim** [comment]
public function encode(string $event, $data)
    {
        $packet = Packet::MESSAGE . Packet::EVENT;
        $shouldEncode = is_array($data) || is_object($data);
        $data = $shouldEncode ? json_encode($data) : $data;
        $format = $shouldEncode ? '["%s",%s]' : '["%s","%s"]';
        return $packet . sprintf($format, $event, $data);
    }

by default this function receives $data as a string or array or object, so the $message attribute data type should not't be string

**Comment by rdrenth** [comment]
In an earlier version it was possible that `$message` could be an array, which resulted the SocketIO payload parser to json_encode the message, but in more recent version it can only be a `string` or `null`. 
And before the event gets pushed, the message (which has to be a string) gets passed to the SocketIO payload parser, which doesn't do anything cause it's already a string.

From the `SwooleTW\Http\Concerns\InteractsWithWebsocket` class:

```php
public function pushMessage($server, array $data)
{
    $pusher = Pusher::make($data, $server);
    $pusher->push($this->payloadParser->encode(
        $pusher->getEvent(),
        $pusher->getMessage()
    ));
}
```

IF this is how it's supposed to be, then you have to `json_encode` your websocket message manually before emitting it, but then the `Websocket::emit();` function should also be strict and only allow a string as $data or am I wrong here?

**Comment by mabdulazim** [comment]
@rdenth 
when you encode the array or the object manually by json_encode() the event doesn’t work

**Comment by albertcht** [comment]
Hi @mabdulazim and @rdrenth ,

Thanks for you clarification, in my original design for `encode` of payload parser, it expects mixed data type as second parameter. However, I neglected this part when I refactor `Pusher`.

Thanks for you pull request :)

**Comment by rdrenth** [comment]
@mabdulazim Indeed, that didn't work, I was only assuming it would work without having it tested, thanks for your PR.
@albertcht Thanks for merging.

**Pull request merged**
