### PR TITLE
Reverted missing fixes PR #417 on FatalThrowableError missing

### PR DESCRIPTION
**Pull request by lagerroos**
Since this for some reason does not exist in the repository I've reverted the fixes of #417 in this PR.

### CODE REVIEW

**Review by Arkanius — CHANGES_REQUESTED** [review]
There's no need to change composer.json

**Comment by Arkanius** [comment]
@lagerroos could you fix it in order to we merge?

**Comment by lagerroos** [comment]
> @lagerroos could you fix it in order to we merge?

So sorry, some stuff came between. I've fixed this now.

**Review by Arkanius — APPROVED** [review]

**Comment by Arkanius** [comment]
Thanks!

**Pull request merged**
