### PR TITLE
Support for laravel/lumen 5.6, 5.7. Code refactoring.

### PR DESCRIPTION
**Pull request by fractalzombie**
Added support for Laravel, Lumen >= 5.6, 5.7. Remove 5.1,5.2 versions, they're old.
Code cleanup.
Fix code style.
Code refactoring.

Prepare to add hot reload (config is already ready), Next PR.

### CODE REVIEW

**Comment by albertcht** [comment]
Hi @fractalzombie ,

Thanks a lot for your PR, do you mind opening another one merging to develop branch? :)

**Comment by albertcht** [comment]
And I will take a look at your pull request soon.

**Comment by fractalzombie** [comment]
@albertcht ok.

**Comment by fractalzombie** [comment]
Go to develop

**Pull request closed without merging**
